import './globals.css';

import type { Metadata } from 'next';

import { Toaster } from '@/components/ui/sonner';
import { getSessionUser } from '@/features/auth';
import { AuthHydration } from '@/features/auth/components/auth-hydration';
import { AuthRequiredModal } from '@/features/auth/components/auth-required-modal';
import { Analytics } from '@vercel/analytics/next';
import { Geist, Geist_Mono, JetBrains_Mono } from 'next/font/google';

const jetBrainsMono = JetBrains_Mono({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getSessionUser();

  return (
    <html lang="en" className={jetBrainsMono.variable}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
        <AuthHydration user={user} />
        <Toaster />
        <AuthRequiredModal />
        <Analytics />
      </body>
    </html>
  );
}
